name: plant_signal
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  #Base
  cupertino_icons: ^1.0.2
  image_picker: ^0.7.4
  image_cropper: ^1.4.0
  modal_bottom_sheet: ^2.0.0
  tflite: ^1.1.2
  google_fonts: ^2.1.0
  path_provider: ^2.0.1
  font_awesome_flutter: ^9.0.0
  nb_utils: ^4.4.8
  intl: ^0.17.0
  flutter_greetings: ^1.0.1

  #Firebase
  firebase_core: ^1.0.3
  cloud_firestore:
  firebase_ml_custom: ^0.2.0
  firebase_auth:

  #Authentication
  google_sign_in: ^5.0.4
  local_auth: ^1.1.6

  # Common
  share: ^2.0.4
  url_launcher: ^6.0.3
  http: ^0.13.3
  html: ^0.15.0
  package_info: ^2.0.2

  #State Management
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1
  get: 4.1.4

  # UI
  fl_chart: 0.36.1
  dots_indicator: ^2.0.0
  otp_text_field: ^1.1.1
  cool_alert: ^1.1.0

  # IMAGES
  cached_network_image: ^3.1.0

  # Generate QR Code #
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.2
  build_runner: ^2.1.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/walletApp/
    - images/crops/
    - fonts/
    - assets/
